### ISSUE TITLE
为参考图菜单添加滚动条/触控板&笔拖动特性

### ISSUE THREAD

**Issue by hathlife** [tylearymf/SETUNA2#10]
现在参考图名单如果项目太多只能点击箭头滚动列表 很麻烦 尤其4k 250%缩放 箭头特别小。。
如果能加入滚动条就好了。
![2020329-211106](https://user-images.githubusercontent.com/19867269/77849973-0f467c00-7202-11ea-9868-b1d7c0aa38cd.png)

**Comment by tylearymf** [comment]
参考图菜单本来就是一个滚动列表，可以用鼠标滚动条滑动的啊
![效果图](https://user-images.githubusercontent.com/14980389/77812168-7b2dc500-70da-11ea-8fd0-0d939158c44c.gif)

**Comment by hathlife** [comment]
@tylearymf  看来是打错字让你误解了 求重开

**Comment by hathlife** [comment]
很好，鼠标滚轮和触控板可以拖动了，但是[笔还是不能拖动](https://h0nm4m31k0.tk/index.php/2020/04/11/tylearymf-setuna2-issues-10/)。。。
似乎笔的拖动和鼠标的不是一套API？
@tylearymf @LJLCarrien

**Comment by tylearymf** [comment]
笔的不知道，我这边没有笔没法测试

**Comment by hathlife** [comment]
@tylearymf  我想到一个方法，把菜单做成可以鼠标左键长按拖动的。您有时间可以试一下吗？

**Comment by tylearymf** [comment]
有时间我看看笔的相关api吧
