### ISSUE TITLE
遇到了一个问题，之前截取的参考图无法显示

### ISSUE THREAD

**Issue by mjchina** [tylearymf/SETUNA2#12]
![QQ图片20200424191610](https://user-images.githubusercontent.com/64259880/80207071-11b0c000-8660-11ea-8ce0-a09fa97da29f.png)
![QQ图片20200424195116](https://user-images.githubusercontent.com/64259880/80209769-3c514780-8665-11ea-90b9-1798f2498c35.png)

![QQ图片20200424191714](https://user-images.githubusercontent.com/64259880/80207142-3442d900-8660-11ea-8b19-4eacf882294a.jpg)

之前有截取一张图片，今天打开setuna后出现如下问题：
1，之前截图的那张图桌面没有显示（确定桌面上没有这张图片的缩小方块）。但在“参考图名单”里面可以看到这张图片，点击后也无法打开。
2，桌面的下方出现了一个虚线选框（如上图），无法去掉，关闭setuna后就没有了，打开setuna就会出现
3，软件能正常截取新的图片，新截取的图片能正常关闭和打开

尝试过反复关闭打开软件，删除程序同目录下的配置文件，改变程序的目录，清除缓存，重置默认配置等等都没有解决这个问题（新截取的图片可以正常被清除），不知道是不是软件在C盘有缓存还是什么原因？请教有没有什么解决办法

谢谢！

**Comment by tylearymf** [comment]
C:\Users\[your pc name]\AppData\Local\SETUNA2，清理下这个目录

**Comment by tylearymf** [comment]
上面这个目录是缓存你的截图记录的

**Comment by mjchina** [comment]
感谢解答
