### ISSUE TITLE
建议：如果可以，希望能有标注功能~

### ISSUE THREAD

**Issue by AnimatorBullet** [tylearymf/SETUNA2#13]
> 首先非常感谢分享！

有点贪心，
因为标注功能现在一直在用snipaste，
对setuna还是很期望能有，只是小建议，
麻烦或者没时间的话不用放心上~再次感谢！

**Comment by tylearymf** [comment]
暂不支持，可以用QQ截图画线后再用该工具来截图，即可实现你的这个想法
