### ISSUE TITLE
BUG：经常会出现截图丢失无法唤出的情况

### ISSUE THREAD

**Issue by ZerOri** [tylearymf/SETUNA2#14]
RT，不知截图溜到哪儿去了，参考图名单选项里还在，但就是无法唤出找到截图，希望增加个点击参考图名单里的截图就能跳出截图的功能以避免此BUG

**Comment by tylearymf** [comment]
目前展开的图片是支持在参考图名单里面点击跳转的，未展开的图片点击是跳转不了的 #11

**Comment by ZerOri** [comment]
> 目前展开的图片是支持在参考图名单里面点击跳转的，未展开的图片点击是跳转不了的 #11

就是未展开的图片跳转不了才头疼，丢失后没法找回来，又得重新截图

**Comment by tylearymf** [comment]
![image](https://user-images.githubusercontent.com/14980389/82285360-dd65c080-99cd-11ea-8fde-12b7ecc83aa1.png)

你把这个勾上

**Comment by ZerOri** [comment]
> ![image](https://user-images.githubusercontent.com/14980389/82285360-dd65c080-99cd-11ea-8fde-12b7ecc83aa1.png)
> 
> 你把这个勾上

没用，勾上截图一样会丢失

**Comment by tylearymf** [comment]
你发下你电脑系统版本和截图软件的版本，然后再录制个截图丢失的视频发我看看

**Comment by tylearymf** [comment]
可以试下该操作
![Image](https://user-images.githubusercontent.com/14980389/103146362-17c4e680-4783-11eb-91eb-a0d91d6db741.png)
