### ISSUE TITLE
建议：希望能把截图时的光标变为FastStone Capture那种贯通全屏的十字光标，以便于截图时参考位置是否准确。

### ISSUE THREAD

**Issue by gittiging** [tylearymf/SETUNA2#15]
建议：希望能把截图时的光标变为FastStone Capture那种贯通全屏的十字光标，以便于截图时参考位置是否准确。

**Comment by tylearymf** [comment]
不是很明白你说的意思，给个视频或者截图之类的说明下

**Comment by gittiging** [comment]
SETUNA截图时鼠标指针
[https://s1.ax1x.com/2020/05/29/tKkb5T.png](url)

FSCapture截图时鼠标指针
[https://s1.ax1x.com/2020/05/29/tKAuZt.png](url)

**Comment by tylearymf** [comment]
已更新
