### ISSUE TITLE
重启系统后参考图消失

### ISSUE THREAD

**Issue by Tollainmear** [tylearymf/SETUNA2#18]
### 1
![image](https://user-images.githubusercontent.com/25898067/85200009-833a8100-b326-11ea-8da7-9b3d92bc73fb.png)
~~如图，无法将截取的图片完全不透明话，影响调色
烦请检查一下相关设置，不然在复杂的图形上放置参考图会影响调色参考（浅色参考图尤其明显）。~~
已解决，是我自己的问题，当窗口焦点不在参考图上的时候，就完全不透明了

### 2
此外，在电脑重启后再次启动Setuna，之前未关闭的参考图不会重新弹出，在右键菜单-“参考图名单”中能够找到，但是在这里点击后没有任何反应，上次未关闭的参考图不会出现，参考图名单内容也不会更新。

### 3
建议将当前Setuna的版本号等基本信息加入到设置面板（而不是启动页面），方便用户检查当前版本

以上问题在版本 2.5.8中发现

**Comment by Anneheng** [comment]
[image](https://github.com/Anneheng/Anneheng.github.io/blob/master/99.pngl)

**Comment by Anneheng** [comment]
![image](https://github.com/Anneheng/Anneheng.github.io/blob/master/99.png)

**Comment by Anneheng** [comment]
粘贴进png格式的图片时，原本背景完全透明的图片变成了不完全透明的图片，希望大佬对png格式图片呈现做一下优化。

**Comment by Tollainmear** [comment]
不需要
