### ISSUE TITLE
在笔记本电脑上外接显示器后选择扩展，截图扩展显示器内容强制跳转主屏幕

### ISSUE THREAD

**Issue by LoliLoita** [tylearymf/SETUNA2#2]
非常感谢作者的高分辨率更新，非常有用。但是今天在笔记本电脑上外接了一台显示器，按win+p选择投影之后再按快捷键截图发现在扩展屏幕上会强行弹出笔记本屏幕的内容导致无法截取扩展屏幕的内容。
以下为我的设备清单：
笔记本电脑：Lenovo-X1-Yoga(win10 企业版)
投影接口：DP
外部显示器：Dell P2314H

**Comment by tylearymf** [comment]
你两边显示器的分辨率是多少，调成一致试下？

**Comment by tylearymf** [comment]
我这边win10，dell双显示器，分辨率一致，截图是没有问题的

**Comment by LoliLoita** [comment]
那可能是我分辨率没有调好，明天再尝试一次。
我的笔记本是2k屏，但扩展显示器是1080的所以可能出现这样的问题。




------------------ 原始邮件 ------------------
发件人: "tylearymf"<notifications@github.com>;
发送时间: 2019年5月14日(星期二) 凌晨0:40
收件人: "tylearymf/SETUNA2"<SETUNA2@noreply.github.com>;
抄送: "Dan"<574977418@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [tylearymf/SETUNA2] 在笔记本电脑上外接显示器后选择扩展，截图扩展显示器内容强制跳转主屏幕 (#2)




我这边win10，dell双显示器，分辨率一致，截图是没有问题的

**Comment by tylearymf** [comment]
> 那可能是我分辨率没有调好，明天再尝试一次。 我的笔记本是2k屏，但扩展显示器是1080的所以可能出现这样的问题。
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "tylearymf"<notifications@github.com>; 发送时间: 2019年5月14日(星期二) 凌晨0:40 收件人: "tylearymf/SETUNA2"<SETUNA2@noreply.github.com>; 抄送: "Dan"<574977418@qq.com>;"Author"<author@noreply.github.com>; 主题: Re: [tylearymf/SETUNA2] 在笔记本电脑上外接显示器后选择扩展，截图扩展显示器内容强制跳转主屏幕 (#2) 我这边win10，dell双显示器，分辨率一致，截图是没有问题的 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

更新最新版看下，已经支持多台不同DPI显示器截图了
