### ISSUE TITLE
显示器DPI超过100%之后截图异常

### ISSUE THREAD

**Issue by JamesHuang0331** [tylearymf/SETUNA2#20]
![image](https://user-images.githubusercontent.com/7420251/86310792-70db1400-bc51-11ea-8a87-0b3ab33c5804.png)
如图，无法截取下方和右方的屏幕。

**Comment by tylearymf** [comment]
在设置界面配置对应的DPI

**Comment by JamesHuang0331** [comment]
> 在设置界面配置对应的DPI

![image](https://user-images.githubusercontent.com/7420251/86335498-296c7c00-bc81-11ea-9c18-6d55cce2ed67.png)
这里已经设置了，但是只能截取左上角的屏幕

**Comment by tylearymf** [comment]
截下你的 系统->显示->分辨率 这个窗口，我看下你的系统设置及分辨率

**Comment by JamesHuang0331** [comment]
> 截下你的 Windows->设置->系统->显示->分辨率 这个窗口，我看下你的系统设置及分辨率

好的
![image](https://user-images.githubusercontent.com/7420251/86352808-f9c96e00-bc98-11ea-8c57-8246b4ec588a.png)

**Comment by tylearymf** [comment]
截下分辨率。。。

**Comment by JamesHuang0331** [comment]
> 截下分辨率。。。

图中有。。2560*1440的

**Comment by tylearymf** [comment]
![image](https://user-images.githubusercontent.com/14980389/86367174-36ec2b00-bcae-11ea-9a4b-04eab52e04f4.png)
改了分辨率后，要重开下截图软件

**Comment by JamesHuang0331** [comment]
> ![image](https://user-images.githubusercontent.com/14980389/86367174-36ec2b00-bcae-11ea-9a4b-04eab52e04f4.png)
> 改了分辨率后，要重开下截图软件

解决了。。[手动捂脸]。。感谢解答
