### ISSUE TITLE
修剪+编辑

### ISSUE THREAD

**Issue by Supelite** [tylearymf/SETUNA2#24]
hi, 感谢大大对setuna的维护，现在setuna已经非常非常棒了，但如果能够在“修剪”操作里添加一些“编辑”功能的话 - 诸如写字、画线 等基础编辑操作，那就更加完美了，希望大大可考虑一下，辛苦辛苦。

**Comment by tylearymf** [comment]
暂不支持，可以用QQ截图画线后再用该工具来截图，即可实现你的这个想法
