### ISSUE TITLE
截图丢失如何找到缓存的图片

### ISSUE THREAD

**Issue by monci1850** [tylearymf/SETUNA2#26]
如题,  我在更换显示器设置的时候出现了截图丢失的情况  只剩下2张, 其余十几张都找不到了.  在右键参考图名单里面可以看到这些丢失的截图, 但是点击并没有任何反应.

**Comment by tylearymf** [comment]
可能是图片位置问题，你打开任务管理器，找到截图软件，展开后里面有n个小进程，双击这些小进程，对应的截图应该就出现了

**Comment by tylearymf** [comment]
![image](https://user-images.githubusercontent.com/14980389/103146362-17c4e680-4783-11eb-91eb-a0d91d6db741.png)
说错了，应该是右键子进程，点击结束

**Comment by chujuhuayu** [comment]
\\软件选项中\常规\打开缓存目录\  此目录下只有当前钉在屏幕上的截图，如果关闭截图，其缓存 目录中截图就消失了，不知是故意设计还是为何。

建议能按时间目录保留，便于查询或再次使用。 
例:
C:\2021-1-29-1452\截图1.png
C:\2021-1-29-1452\截图2.png

C:\2021-1-30-1201\截图1.png
C:\2021-1-30-1201\截图2.png

或者不要时间目录，任何时间的截图都保留在同一目录也是可以的。

**Comment by tylearymf** [comment]
该功能已加入TODO，后续再加
