### ISSUE TITLE
建议：希望增加一个一键关闭所有参考图的功能

### ISSUE THREAD

**Issue by bubblyhanzo** [tylearymf/SETUNA2#27]
有时候重启电脑后部分参考图不在显示屏上，但是那部分参考图还是在参考图名单里，无法手动拖出来也无法关闭。希望增加一键关闭所有参考图功能，或者可以把参考图从参考图名单里拖出来的功能。

**Comment by tylearymf** [comment]
已更新

**Comment by tylearymf** [comment]
右键 托盘菜单中的 程序图标 -> 关闭所有截图 
![image](https://user-images.githubusercontent.com/14980389/103761144-2ba8fc00-5051-11eb-84a5-31303945675c.png)
