### ISSUE TITLE
关于截屏之后截图略有放大而影响清晰度的问题

### ISSUE THREAD

**Issue by aecra** [tylearymf/SETUNA2#28]
如题，在截屏后展现

的截图会较原有大小有所放大，而这就使得图片清晰度很明显的降低了，希望可以解决这个问题

![屏幕截图 2021-01-18 131455](https://user-images.githubusercontent.com/34883050/104875136-8286cd80-598f-11eb-9b95-b5007a91f58a.png)

**Comment by aecra** [comment]
把图片保存下来后清晰度没问题

**Comment by tylearymf** [comment]
windows版本是？，setuna版本是？

**Comment by aecra** [comment]
版本1909（OS18323.1256）
3.0.0.6
1080p 100%

**Comment by MOOA-code** [comment]
也是一样的情况；
版本2004（OS19041.508）
3.0.0.6
1080p 100%

**Comment by tylearymf** [comment]
> 也是一样的情况；
> 版本2004（OS19041.508）
> 3.0.0.6
> 1080p 100%

你截图后，一个保持默认样式，一个右键选个 缩放为100% 样式，然后把这两个图截在一起，我看下效果。

**Comment by tylearymf** [comment]
> > 也是一样的情况；
> > 版本2004（OS19041.508）
> > 3.0.0.6
> > 1080p 100%
> 
> 你截图后，一个保持默认样式，一个右键选个 缩放为100% 样式，然后把这两个图截在一起，我看下效果。

我这边是 4k 250%，暂时不会出现截图后放大问题，所以需要你那边搞个效果图来看看

**Comment by aecra** [comment]
这是截的图
![2021-01-23 13-04-22-14](https://user-images.githubusercontent.com/34883050/105569388-2996ab00-5d7c-11eb-992a-5a6de47f1ca9.png)
![2021-01-23 13-04-36-56](https://user-images.githubusercontent.com/34883050/105569389-2ac7d800-5d7c-11eb-8089-6fc8419aa5be.png)
这两个是效果，上面那个是默认的，下面这个是100%，不过这俩好像没区别
![2021-01-23 13-05-15-76](https://user-images.githubusercontent.com/34883050/105569390-2b606e80-5d7c-11eb-95e5-ed9461ee7b91.png)
![2021-01-23 13-05-30-23](https://user-images.githubusercontent.com/34883050/105569391-2bf90500-5d7c-11eb-8f53-e012922f22d5.png)
这个图，上边框和左边框有一个白色的线条，右边框和下边框没有
![2021-01-23 13-08-35-03](https://user-images.githubusercontent.com/34883050/105569393-2c919b80-5d7c-11eb-83b6-0ca7802aaa09.png)

**Comment by tylearymf** [comment]
"这个图，上边框和左边框有一个白色的线条，右边框和下边框没有"
这个是原来的SETUNA的功能来的

**Comment by tylearymf** [comment]
> 这是截的图
> ![2021-01-23 13-04-22-14](https://user-images.githubusercontent.com/34883050/105569388-2996ab00-5d7c-11eb-992a-5a6de47f1ca9.png)
> ![2021-01-23 13-04-36-56](https://user-images.githubusercontent.com/34883050/105569389-2ac7d800-5d7c-11eb-8089-6fc8419aa5be.png)
> 这两个是效果，上面那个是默认的，下面这个是100%，不过这俩好像没区别
> ![2021-01-23 13-05-15-76](https://user-images.githubusercontent.com/34883050/105569390-2b606e80-5d7c-11eb-95e5-ed9461ee7b91.png)
> ![2021-01-23 13-05-30-23](https://user-images.githubusercontent.com/34883050/105569391-2bf90500-5d7c-11eb-8f53-e012922f22d5.png)
> 这个图，上边框和左边框有一个白色的线条，右边框和下边框没有
> ![2021-01-23 13-08-35-03](https://user-images.githubusercontent.com/34883050/105569393-2c919b80-5d7c-11eb-83b6-0ca7802aaa09.png)

看你截的对比图好像不会变模糊呀

**Comment by aecra** [comment]
那两个分开的小图是截图后保存到本地的，这个是清楚的
后面那俩是截图后展示出来的。我试了100%，但这个和默认展示的都是会略有放大，就显得模糊了，就是两个展示图在一起的截图，这俩展示出来的都是模糊的

**Comment by MOOA-code** [comment]
![剪贴板-20210124](https://user-images.githubusercontent.com/54346272/105628187-6a72ea80-5e76-11eb-889b-e03988ae32c7.png)
左边是默认样式，右边是缩放为100%；感觉缩放为100%后更模糊了一点

**Comment by tylearymf** [comment]
好的，我在其他 1080p 电脑上重现了这个问题了，后面有时间再修复了

**Comment by tylearymf** [comment]
好的，我在其他 1080p 电脑上重现了这个问题了，后面有时间再修复了

**Comment by aecra** [comment]
刚试了下3.0.0.5，没有这个问题

**Comment by tylearymf** [comment]
好的

**Comment by tylearymf** [comment]
@aecra @MOOA-code 你们试下在 3.0.0.6 下把这个开启下看看，在 **杂项设置** -> **截图背景**
![image](https://user-images.githubusercontent.com/14980389/106278910-7f84ba80-6276-11eb-88f3-3f22907f950e.png)

**Comment by MOOA-code** [comment]
嗯，这样就正常了👍

Sherry <notifications@github.com> 于2021年1月29日周五 下午9:12写道：

**Comment by chujuhuayu** [comment]
你好作者，除上以上朋友所陈述的图像清晰度的问题外，我还发现了另一个BUG，即电脑首次开机启动此软件或平时，偶尔会出现影响输入的问题。比如我现在要更改一个文件的文件名，可以发现刚输入2个字母，其更改文件名的地方焦点就失焦了，即无法输入相当于鼠标点击空白处一样的效果。只要退出你这个软件就一切正常了。再次打开你的软件也可以正常输入了。

还有就是有一次也是更改文件名，在输入字母时发现居然触发了截屏功能，可是截屏功能快捷键明明是ctrl+alt+e，理论上是不可能冲突和触 发的。因当时只是输入字母未使用功能键！！！

出现以上问题的版本是3.0.0.6!!! 请知悉和分析是否确定是软件BUG   谢谢

**Comment by tylearymf** [comment]
这个会记录的，后面有时间再看了

**Comment by chujuhuayu** [comment]
> 这个会记录的，后面有时间再看了

我好像明白为啥会影响更改文件名了即焦点消失的问题，就如截图软件V3.0.05的版本发布时的更新记录一样。如下：
【Fixed 其他软件在右键时有时会被截图刷新置顶给取消掉】
我想应该还是这个问题导致的！

**Comment by tylearymf** [comment]
> > 这个会记录的，后面有时间再看了
> 
> 我好像明白为啥会影响更改文件名了即焦点消失的问题，就如截图软件V3.0.05的版本发布时的更新记录一样。如下：
> 【Fixed 其他软件在右键时有时会被截图刷新置顶给取消掉】
> 我想应该还是这个问题导致的！

是的，后续我查下
