### ISSUE TITLE
Win7 设置报错

### ISSUE THREAD

**Issue by AlgerQc** [tylearymf/SETUNA2#3]
![image](https://user-images.githubusercontent.com/38353834/61781782-8fc50980-ae37-11e9-8380-2e52e1bbac32.png)

Win7系统对软件进行设置后,点击确定就会出现这个弹窗,弹窗关闭后设置可以被保存,并没感觉到其他的影响

**Comment by tylearymf** [comment]
这个是开机启动的，我后面修下
