### ISSUE TITLE
截图多张以后点击其它的程序窗口，某几张图就会被盖住

### ISSUE THREAD

**Issue by yaukeywang** [tylearymf/SETUNA2#4]
这个问题好像原版本就有，有时候截图5张或者更多，有些截图就不能置顶了，经常被盖住要最小化其它窗口找半天才能找到，很不方便，是否能麻烦作者帮大家修复下这个bug呢：）

**Comment by tylearymf** [comment]
嗯，我后面修下

**Comment by yaukeywang** [comment]
问题依然存在，复现方式：在某一个应用窗口上，不断截图，截图到第6张或者以上，然后点击下面的应用程序，那么大概率前四章图就被盖下去了。
Ps:现在还多了一个bug，可能是为了窗口置顶，比如微信截图（或者其他软件截图）的时候，使用setuna截的图，会跑到其他截图操作界面上，之前的版本不会。

**Comment by tylearymf** [comment]
好的，我后面有空处理
