### ISSUE TITLE
把参考图拖到屏幕边缘，然后缩小会跑出屏幕范围之外，找不回来了

### ISSUE THREAD

**Issue by qq449265558** [tylearymf/SETUNA2#40]
**Describe the bug (简要描述下问题)**

**Steps to reproduce the behavior (重现问题的步骤)**

**Expected behavior (期望行为)**

**Screenshots (问题相关的截图)**

**Environment (环境信息)**

 - Windows Version: [e.g. Win10 19042.746]
 - Screen DPI: [e.g. 125%]
 - SETUNA Version: [e.g. 3.0.0.1]

**Additional context (其他信息，例如日志)**

**Comment by tylearymf** [comment]
重开软件
