### ISSUE TITLE
2.5.1无法调整程序的大小

### ISSUE THREAD

**Issue by UnuboreJoe** [tylearymf/SETUNA2#5]
只能那么大，用箭头拉不动

**Comment by UnuboreJoe** [comment]
补充一下，是能调大，调不了小

**Comment by tylearymf** [comment]
能录个视频或者gif看看吗

**Comment by UnuboreJoe** [comment]
[url=https://sm.ms/image/ioXsEZuAjn8qykt][img]https://i.loli.net/2019/08/14/ioXsEZuAjn8qykt.gif[/img][/url]
2.4.1

[url=https://sm.ms/image/1txywWqLVZr8jT3][img]https://i.loli.net/2019/08/14/1txywWqLVZr8jT3.gif[/img][/url]
2.5.1

**Comment by tylearymf** [comment]
ok，了解了
