### ISSUE TITLE
截图之后  图片的透明度能设置成0嘛?

### ISSUE THREAD

**Issue by feimeng2017** [tylearymf/SETUNA2#6]
我截图一般是跟前面的图做对比(修改之后和之前的对比). 发现截完的图是带有一点透明度的(不仔细看不出来),这样就影响前后的对比, 设置了一下设置里面的两个百分比, 但是不起作用,只能使用右键的增加透明度,每次截完都要右键点一下,能默认成不透明嘛?? 在鼠标不触碰截图的情况下     
谢谢

**Comment by tylearymf** [comment]
我后面看看

**Comment by tylearymf** [comment]
![1](https://user-images.githubusercontent.com/14980389/64313537-886c5080-cfde-11e9-9e9c-6cf352ed6c8a.png)
![2](https://user-images.githubusercontent.com/14980389/64313555-991cc680-cfde-11e9-8bc6-0780306127a5.png)
![3](https://user-images.githubusercontent.com/14980389/64313566-9d48e400-cfde-11e9-84da-6df40879113d.png)
![4](https://user-images.githubusercontent.com/14980389/64313573-a20d9800-cfde-11e9-94e9-5b7aa20e3bfe.png)

@feimeng2017 按这个步骤操作下，因为默认截完图是走“基本自动操作”逻辑的，所以你如果有特殊需求的可以在“基本自动操作”里面加
