### ISSUE TITLE
回收站功能我这边还是不正常，关机开机之后就丢了（win10 1083）

### ISSUE THREAD

**Issue by MOOA-code** [tylearymf/SETUNA2#7]
你好，很高兴你能接手这个软件的开发，很喜欢这个软件，但是想提几个建议。       
一直在用2.2.1.0这个版本，但是回收站功能并不完善，会丢图，换了你最新的那个版本，
测试了一下，还是一样。还有参考图名单这个功能也是有问题的，它们显示的时候老是在屏幕左上角，这个体验不太好。
现在就是非常想要历史纪录这个功能，因为经常就是随手贴图，不会特意保存原图，所以有时候想用之前的图，却发现没了。。。还得再找原图，再重新贴一下。。。
所以希望作者大大能够把这个功能给完善一下，非常感谢。

**Comment by tylearymf** [comment]
你说的这几个功能在最新版2.5.3都有，你使用的时候，把下载的2.5.3放到一个新的文件夹里试下，不要跟以前版本的混在一起

**Comment by tylearymf** [comment]
还有有问题的地方要写明具体情况
