### ISSUE TITLE
exe文件闪退

### ISSUE THREAD

**Issue by SiRumCz** [tylearymf/SETUNA2#8]
你好，因为我不熟悉vs build流程，所以可能会犯低级错误， 请谅解。我在macos上用visual studio build了这个项目后把exe拉到了win10系统上想跑起来发现每次一点开就会马上闪退。请问一下原因是什么呢。多谢。

**Comment by tylearymf** [comment]
你把你的exe压缩一下发我一份，我帮你看看

**Comment by SiRumCz** [comment]
[SETUNA.tar.gz](https://github.com/tylearymf/SETUNA2/files/3933497/SETUNA.tar.gz)
十分感谢！

**Comment by tylearymf** [comment]
你build出来的exe大小就不对了，正确的应该是1.5M左右，你的才57K，我这边用的vs2019，你可能也需要对下版本，还有个，你可以做个小测试，用vs新建个空白的控制台工程，然后尝试build后，看在win下能不能运行

**Comment by SiRumCz** [comment]
抱歉，这个好像是因为我第一次压缩时指令用错了覆盖了文件。 这次应该是对的。
[SETUNA.exe.tar.gz](https://github.com/tylearymf/SETUNA2/files/3935734/SETUNA.exe.tar.gz)

另外其实我是想在自己电脑上使用这个软件，如果可以，能否能直接发我一份可以在win10上使用的exe文件呢？

**Comment by tylearymf** [comment]
release里面可以下载最新版本

**Comment by SiRumCz** [comment]
非常感谢！
